version: '3'
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    command: [start-kafka.sh]
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
