version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.29.1
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro"
    networks:
      - myNetwork
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 3000:3000
    networks:
      - myNetwork
    depends_on:
      - prometheus
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - myNetwork
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    hostname: zookeeper
    networks:
      - myNetwork
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    command: [start-kafka.sh]
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - myNetwork
networks:
  myNetwork:
    name: pursuit_network
